"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.router = void 0;
const express_1 = require("express");
const controller_1 = require("../../api/v1/qrcode/controller");
const controller_2 = require("../../api/v1/message/controller");
const router = (0, express_1.Router)();
exports.router = router;
const qrCodeController = new controller_1.QRCodeController();
const messageController = new controller_2.MessageController();
router.get("/qrcode", qrCodeController.getQRCodeImageStream);
router.get("/send-text", messageController.sendText);
